# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Backend Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: cd ./backend
      - run: npm install
      - run: npm test

      - uses: actions/checkout@v4
      - name: Frontend Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: cd ./frontend
      - run: npm install
      - run: npm lint
      - run: npm run build

      - name: test building backend docker image
        run: cd ./backend && docker build -t ci-cd:backend .

      - name: test building frontend docker image
        run: cd ./frontend && docker build -t ci-cd:frontend .
